[package]
name = "modmod"
version = "0.1.0"
authors = ["Anderson Mills <anderson@puppet.com>"]

[[bin]]
name = "modmod"
path = "src/modmod.rs"

[dependencies]
docopt = "0.7"
rustc-serialize = "0.3"
git2 = "0.6"
